language: node_js
node_js:
- '6'
env:
  global:
  - secure: AxSVJPVDsd7sYUQglK/FTBKGNEK6U/xngAzedXZxruF8BWuVDbPdaRS6BhrpgY4hdychK9vYTeDLcdRtyPzNhdyL3uzLcg2H9ifJyPRgaHUVRQZ0er5b1mIF5be/pPKVv5DV5iW+BtU09yZfLX6j2Nh4Pqyj6Sp+nJFgZB/ntJGPwr7qASyQyG4xHHfneOmaHd3xbzRKEtGW672rbhNl22LDCM7yRpymZpf+iWL2nHurVJJnnRetb+pvgYJZuRYinOoilrYiTxyumqye/PYU4CSPwAZSD8eP2RElWNW8ROQOtgm2pA4XslBn0f+Qk4ExlJoc5PC5UAfTN+LI1lgEo2F5r4tmyZyimC5hr5t66suYtBxJHwbzSsF43wcBMfPjRHxM7LFrujvc130T2ja823GQHOc6XBMxi9A5leZ6Ze+RfJR+u+0s7E7Hls86pAeNVZtOhw8mMjfqHZY1NvFtkLWKxpEiEp42/qS6RjyjvxkQhaMvIa8fHzE5V5uXfITU1bQRAkchyHra10+Ft3846ivi3aMw0U18QZxEiBRliHN6qNZBMydpEm+ikiDE8LP+TK+Q/uHU8DZ6kmKKJoHTLx2ou69PFVZQMfnSq7iGAdQZTtenu3iX3ZLq2jzDizsXWqMvnDCrXlcNLptHe3aVfkegh1kNJwfLRxYRsLnPKBk=
