language: node_js
node_js:
- '6'
env:
  global:
    secure: Z/bMPYNLsM4kqO0JweQEqdT4qRmqxiVL+3fimUuJJCmOyvcoyztJlY8bzi3cTrBtvGK/d49F/w1j2TWSoJaOfXRDI+hq7CGtTveoegyJO6xvWId2FRdLzrTyNms4t4SWHuioOzh9VL7YgN02ipqs9zQuiUxABn3EoFT0r+VUmxCHLOpy3UlxX8TqZfk+uGAb+y9FMO+gMfr9SfvhBZWcIEgyPj8/W7HX2dYbY7hommkraQkkUw8b17r2sBJoZsR/w41DVg9BNF3N0EBPWSt3BBeMG4jAxihW9CNOUSLadGY5Pt1s0TIWDrfSKi2tdnsKHKw0MPE7nCjM8rJcdq/YaBGYzxPRvsk5LsghOCP/o0IMgtnBl/H5R1cfgxxMzwllpTauK+1Y02I3hoot5ADNeyOEeUMPsPsNUe4AosWKZ86rCeacxB1BOrlPqJ06DurD9ziCn8Zy38FOQbtumphrX9cRpakwDocDpqAUYwH3D6Ieb3Lp6eMr+V5IjdLDIu5EQOwgPBkkH6StCi3x4ZI7pCVtfE2DPRTQCtic03ygS9sf+Ln9b+V+Ao6+D94ey0tmSO6GFqyaScVvUDF62UijKAaZVVeMswXn7+9lTVbT8e6G+ap9YVezhENGfsllHDauzLsEihw5z9l2Ig+BfSd+qBQ3i134VIod1GjECfJ2Sdo=
