language: node_js
node_js:
- '6'
services:
- docker
before_script:
- docker-compose up -d
env:
  global:
    secure: V0XIJ8qkO+8x3eyMud9GMbPToIMz0NdycuczKrZdr2h4xTMMNuWfV/HI5FduCiFDU5i/OjYVgDn8sz9o4ioxnAnJ/DSEyDIHXCL9cJLkYUdtkGzRZ66ccviyAFLh41AJuVc1hfMPDVFNOs7lZ2eoLid19J+R5YyvapXCVnpJNye1tnxMYIuqrKG1mVXI5ZYo5eF89Xjejkn3dpPKLl2zz3lsrVatImI5XrH0veVWoHOI2bwjvkEbYbw0JAlfMo5gjUtGSZDHc7HMFHoYBeV+aLYshsJ4tV/+fkoHapqRW3O6Haf0rfd2ZZTmcphd5fc3Cifu/VLX2klVzjTqfV33Fsu6XzVhh5BaUxNJ7/FXhMmaZ3/h94XZjfcEd/1aQs4CVqnQ9UPwe5xheXo4JlC61HcxyILmkiDdxida6UDFvJ5w6QMw/aRyyg4jyUBEj17weJFt9uCRuesrDUKYgVnaK52PTpBxOWngfK9FKzK9KYu4YHL2zlXXdANvPbAXM84WQGkMrRx82u+06QHmPiltODi6ey7xDlKeP2Wdcyt746RKH4D6CoFD0+sLOQTaNn4oBXbogkRJsxv+2QwqGtwIUx8A63SxzwDRKVX3OetaMZW3K0EIVUYbGzUVadX0Ppbek43DNCLsXnNnp3nBzXzQZOuuaS9T5njsHCCZgav0V0w=
