#!/bin/bash

set -e

urlencode() {
    # urlencode <string>

    local length="${#1}"
    for (( i = 0; i < length; i++ )); do
        local c="${1:i:1}"
        case $c in
            [a-zA-Z0-9.~_-]) printf "$c" ;;
            *) printf '%s' "$c" | xxd -p -c1 |
                   while read c; do printf '%%%s' "$c"; done ;;
        esac
    done
}

urldecode() {
    # urldecode <string>

    local url_encoded="${1//+/ }"
    printf '%b' "${url_encoded//%/\\x}"
}

check() {
  local key="$1"; shift

  local value="${!key}"

  if [[ -z $value ]]
  then
    echo "Missing environment variable $key"
    exit 1
  fi
}

check BROKER

opts=()
opts+=(-h "$BROKER")
opts+=(-t "/bitraf/tv/showmessage")

if [[ ! -z $MQTT_USERNAME ]]
then
  opts+=(--username "$MQTT_USERNAME" --pw "$MQTT_PASSWORD")
fi

echo "Connecting to MQTT"
mosquitto_sub "${opts[@]}" | while read first rest_of_line
do
  message="${first} ${rest_of_line}"
  URL=http://tv.local:8080/message/$(urlencode "${message}")
  echo "opening" $URL
  DISPLAY=:0 zenity --text-info --html --url $URL --width 1824 --height 1084 --timeout 5 &
done
sleep 1
