version: '2'
services:
  mqtt:
    image: ansi/mosquitto
    container_name: bitraf-mqtt
    ports:
      - '127.0.0.1:1883:1883'
    entrypoint: /usr/local/sbin/mosquitto
  influxdb:
    image: influxdb
    container_name: influxdb
    ports:
      - '127.0.0.1:8086:8086'
  msgflo:
    build: .
    container_name: bitraf-iot
    environment:
      MSGFLO_BROKER: 'mqtt://mqtt:1883'
    ports:
      - '127.0.0.1:3569:3569'
    links:
      - mqtt
  openmct:
    image: cbase/cbeam-telemetry-server
    container_name: cbeam-telemetry-server
    command: node bitraf.js
    environment:
      MSGFLO_BROKER: 'mqtt://mqtt:1883'
      INFLUX_HOST: influxdb
    ports:
      - '127.0.0.1:8080:8080'
      - '127.0.0.1:8082:8082'
    links:
      - influxdb
      - mqtt
