name: Build and push p2k16-label docker image

on:
  release:
    types: [published]

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest

    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get the version
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})

      - name: Build image and push to  GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./p2k16-label
          # Note: tags has to be all lower-case
          tags: |
            ghcr.io/bitraf/p2k16-label:${{steps.vars.outputs.tag}}
            ghcr.io/bitraf/p2k16-label:latest
          # build on feature branches, push only on master branch
          push: ${{ github.ref == 'refs/heads/master' }}

      - name: Debug info
        run: echo "debug: github.ref = ${GITHUB_REF} "
